on:
  push:
    branches:
      - master
    tags:
      - v*

---

- name: Publish gem on tag push
  uses: dawidd6/action-publish-gem@v1.2.0
  with:
    # Optional, will publish to RubyGems if specified
    api_key: ${{secrets.RUBYGEMS_API_KEY}}
    # Optional, will publish to GitHub Packages if specified
    github_token: ${{secrets.GITHUB_TOKEN}}
