name: Publish gem on tag push
on:
  push:
    tags:
      - 'v*' 
      - '!v**-mconf*'
# Tags that will trigger: v1.9.0; v1.9.0-beta1
# Tags excluded (with the '!'): v1.9.0-mconf; v1.9.0-mconf-beta1

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: dawidd6/action-publish-gem@v1.2.0
        with:
          # Optional, will publish to RubyGems if specified
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
